print("ravi")
print("pooja")
print("mintu")
print("mukesh")
print("local main")
print("remote main")
print("new")
print("fetch")
print("this is in the main local")
print("this is second update in mintu branch")
print("to merge")
print("in mintu branch")
print("final edit in mintu branch")
print("rebase edited in main")
print("learn rebase")
print("ravi")
print("mintu")
print("i changed in local main branch")
print("change in the local mintu branch")
print("add in mintu branch")
print(main branch updated on remote")
